"""
domain/executive_report.py

Internal domain models for AI Executive Business Research Report.

Encapsulates the structured C-suite intelligence report synthesized from ResearchContext.
Contains 8 mandatory sections: Executive Summary, Commercial Opportunity, Clinical Landscape,
Market Analysis, Patent Landscape, Scientific Momentum, Key Strategic Risks, and Investment Recommendation.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class ExecutiveReport:
    """
    Structured C-suite strategic intelligence report.
    Generated by ExecutiveReportService from normalized ResearchContext data.
    """
    summary:                str  # 1. Executive Summary
    commercial_opportunity: str  # 2. Commercial Opportunity
    clinical_analysis:      str  # 3. Clinical Landscape
    market_analysis:        str  # 4. Market Analysis
    patent_analysis:        str  # 5. Patent Landscape & FTO
    scientific_analysis:    str  # 6. Scientific Momentum
    risks:                  str  # 7. Key Strategic Risks
    recommendation:         str  # 8. Investment Recommendation
    generated_at:           str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    model_name:             str = "gemini-2.5-flash"
